import type { Metadata } from "next";
import { Container } from "@/components/Container";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "The Blog",
    template: "%s | The Blog",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <Container>
        <Header />
        <body>{children}</body>
      </Container>
      <Footer />
    </html>
  );
}
